spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  redis:
    port: 6379
    host: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: campusmeet123@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: ${JWT_SECRET_KEY}